# Generated by Django 4.2.5 on 2023-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=32)),
                ('quantity', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
            ],
        ),
    ]
